Algoritmo "BoasVindas"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Thiago
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Yuri Conder
// Data atual  : 17/11/2021
Var
// Seção de Declarações das variáveis 
   nome:caractere


Inicio
   Escreva ("Bom dia,insira o seu nome ao lado:")
   Leia (nome)
   EscrevaL ("Seja bem vindo(a) ",nome,"!")
Fimalgoritmo